# Generated by Django 5.2.17 on 2026-08-18 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DicionarioAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('created_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Criado por (ID do Usuário)')),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Atualizado por (ID do Usuário)')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de Exclusão Lógica')),
                ('deleted_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Excluído por (ID do Usuário)')),
                ('nome_atributo', models.CharField(max_length=50, unique=True, verbose_name='Nome do Atributo Técnico')),
            ],
            options={
                'verbose_name': 'Atributo Descritivo',
                'verbose_name_plural': 'Atributos Descritivos',
                'db_table': 'dicionario_atributos',
                'ordering': ['nome_atributo'],
            },
        ),
        migrations.CreateModel(
            name='DicionarioUom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('created_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Criado por (ID do Usuário)')),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Atualizado por (ID do Usuário)')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de Exclusão Lógica')),
                ('deleted_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Excluído por (ID do Usuário)')),
                ('sigla', models.CharField(max_length=10, unique=True, verbose_name='Sigla da Unidade (ex: kg, m, UN)')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição da Unidade')),
            ],
            options={
                'verbose_name': 'Unidade de Medida (UOM)',
                'verbose_name_plural': 'Unidades de Medida (UOM)',
                'db_table': 'dicionario_uom',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('created_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Criado por (ID do Usuário)')),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Atualizado por (ID do Usuário)')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de Exclusão Lógica')),
                ('deleted_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Excluído por (ID do Usuário)')),
                ('nome', models.CharField(db_index=True, max_length=255, verbose_name='Nome do Item / Insumo')),
                ('fator_conversao', models.DecimalField(decimal_places=4, default=1.0, max_digits=12, verbose_name='Fator de Conversão (Compra -> Consumo)')),
                ('ultimo_custo_compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Último Custo de Compra (R$)')),
                ('data_ultima_compra', models.DateTimeField(blank=True, null=True, verbose_name='Data da Última Compra')),
                ('tipo_uso', models.CharField(choices=[('Insumo Produtivo', 'Insumo Produtivo'), ('Material de Consumo', 'Material de Consumo'), ('EPI', 'EPI'), ('Ferramental', 'Ferramental')], default='Insumo Produtivo', max_length=30, verbose_name='Tipo de Uso')),
                ('unidade_compra', models.ForeignKey(db_column='unidade_compra_id', on_delete=django.db.models.deletion.PROTECT, related_name='itens_unidade_compra', to='catalogo.dicionariouom', verbose_name='Unidade de Compra')),
                ('unidade_consumo', models.ForeignKey(blank=True, db_column='unidade_consumo_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_unidade_consumo', to='catalogo.dicionariouom', verbose_name='Unidade de Consumo / Fracionamento')),
            ],
            options={
                'verbose_name': 'Item / Insumo',
                'verbose_name_plural': 'Itens e Insumos',
                'db_table': 'itens',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemAtributoValor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=255, verbose_name='Valor do Atributo')),
                ('atributo', models.ForeignKey(db_column='atributo_id', on_delete=django.db.models.deletion.PROTECT, related_name='itens_valores', to='catalogo.dicionarioatributo', verbose_name='Atributo Técnico')),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='atributos_valores', to='catalogo.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Valor de Atributo do Item',
                'verbose_name_plural': 'Valores de Atributos dos Itens',
                'db_table': 'item_atributos_valores',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('created_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Criado por (ID do Usuário)')),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Atualizado por (ID do Usuário)')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de Exclusão Lógica')),
                ('deleted_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Excluído por (ID do Usuário)')),
                ('nome', models.CharField(db_index=True, max_length=255, verbose_name='Nome do Produto / Serviço Composto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição / Especificação Técnica')),
                ('tempo_estimado_execucao', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Tempo Estimado de Mão de Obra (Horas)')),
                ('unidade_venda', models.ForeignKey(db_column='unidade_venda_id', on_delete=django.db.models.deletion.PROTECT, related_name='produtos_unidade_venda', to='catalogo.dicionariouom', verbose_name='Unidade de Venda')),
            ],
            options={
                'verbose_name': 'Produto / Receita',
                'verbose_name_plural': 'Produtos e Receitas',
                'db_table': 'produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantidade_utilizada', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Quantidade Utilizada (na Unidade de Consumo)')),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.PROTECT, related_name='fichas_tecnicas_onde_usado', to='catalogo.item', verbose_name='Item / Matéria-Prima Utilizada')),
                ('produto', models.ForeignKey(db_column='produto_id', on_delete=django.db.models.deletion.CASCADE, related_name='ficha_tecnica_itens', to='catalogo.produto', verbose_name='Produto Pai')),
            ],
            options={
                'verbose_name': 'Item da Ficha Técnica (BOM)',
                'verbose_name_plural': 'Itens das Fichas Técnicas (BOM)',
                'db_table': 'ficha_tecnica',
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['nome'], name='idx_item_nome'),
        ),
        migrations.AddConstraint(
            model_name='itematributovalor',
            constraint=models.UniqueConstraint(fields=('item', 'atributo'), name='unique_item_atributo'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['nome'], name='idx_produto_nome'),
        ),
        migrations.AddConstraint(
            model_name='fichatecnica',
            constraint=models.UniqueConstraint(fields=('produto', 'item'), name='unique_produto_item_ficha'),
        ),
    ]
