# Generated by Django 5.2.17 on 2026-08-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tipo_uso',
            field=models.CharField(choices=[('INSUMO_PRODUTIVO', 'INSUMO PRODUTIVO'), ('MATERIAL_CONSUMO', 'MATERIAL DE CONSUMO'), ('EPI', 'EPI'), ('FERRAMENTAL', 'FERRAMENTAL')], default='INSUMO_PRODUTIVO', max_length=30, verbose_name='Tipo de Uso'),
        ),
    ]
