# Generated by Django 5.2.17 on 2026-08-18 11:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('faturamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('created_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Criado por (ID do Usuário)')),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Atualizado por (ID do Usuário)')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de Exclusão Lógica')),
                ('deleted_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Excluído por (ID do Usuário)')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Conta / Caixa')),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Atual (R$)')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Limite de Cheque Especial (R$)')),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
                'db_table': 'contas_bancarias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MeioPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('created_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Criado por (ID do Usuário)')),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Atualizado por (ID do Usuário)')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de Exclusão Lógica')),
                ('deleted_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Excluído por (ID do Usuário)')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Meio de Pagamento')),
                ('permite_taxa_maquininha', models.BooleanField(default=False, verbose_name='Permite Desconto de Taxa de Maquininha')),
                ('ativo', models.BooleanField(default=True, verbose_name='Meio Ativo')),
            ],
            options={
                'verbose_name': 'Meio de Pagamento',
                'verbose_name_plural': 'Meios de Pagamento',
                'db_table': 'meios_pagamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('created_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Criado por (ID do Usuário)')),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Atualizado por (ID do Usuário)')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de Exclusão Lógica')),
                ('deleted_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Excluído por (ID do Usuário)')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('tipo', models.CharField(choices=[('Receita', 'Receita'), ('Despesa', 'Despesa'), ('Transferência', 'Transferência (Neutra pro DRE)')], default='Receita', max_length=20, verbose_name='Tipo de Categoria')),
                ('categoria_pai', models.ForeignKey(blank=True, db_column='categoria_pai_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='financeiro.categoriafinanceira', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name': 'Categoria Financeira',
                'verbose_name_plural': 'Categorias Financeiras',
                'db_table': 'categorias_financeiras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('created_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Criado por (ID do Usuário)')),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Atualizado por (ID do Usuário)')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de Exclusão Lógica')),
                ('deleted_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Excluído por (ID do Usuário)')),
                ('nome', models.CharField(max_length=100, verbose_name='Identificação do Cartão')),
                ('dia_vencimento', models.IntegerField(verbose_name='Dia de Vencimento')),
                ('dia_fechamento_padrao', models.IntegerField(verbose_name='Dia de Fechamento Padrão')),
                ('limite', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Limite do Cartão (R$)')),
                ('permite_limite_emergencial', models.BooleanField(default=False, verbose_name='Permite Limite Emergencial')),
                ('conta_bancaria', models.ForeignKey(blank=True, db_column='conta_bancaria_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartoes_credito', to='financeiro.contabancaria', verbose_name='Conta Preferencial de Pagamento')),
            ],
            options={
                'verbose_name': 'Cartão de Crédito Corporativo',
                'verbose_name_plural': 'Cartões de Crédito Corporativos',
                'db_table': 'cartoes_credito',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FaturaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('created_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Criado por (ID do Usuário)')),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Atualizado por (ID do Usuário)')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de Exclusão Lógica')),
                ('deleted_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Excluído por (ID do Usuário)')),
                ('mes_referencia', models.CharField(max_length=7, verbose_name='Mês de Referência (YYYY-MM)')),
                ('data_fechamento_real', models.DateField(verbose_name='Data de Fechamento Real')),
                ('status', models.CharField(choices=[('Aberta', 'Aberta'), ('Fechada', 'Fechada'), ('Paga', 'Paga')], default='Aberta', max_length=20, verbose_name='Status da Fatura do Cartão')),
                ('cartao', models.ForeignKey(db_column='cartao_id', on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='financeiro.cartaocredito', verbose_name='Cartão de Crédito')),
            ],
            options={
                'verbose_name': 'Fatura de Cartão de Crédito',
                'verbose_name_plural': 'Faturas de Cartão de Crédito',
                'db_table': 'faturas_cartao',
                'ordering': ['-mes_referencia'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('created_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Criado por (ID do Usuário)')),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Atualizado por (ID do Usuário)')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de Exclusão Lógica')),
                ('deleted_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Excluído por (ID do Usuário)')),
                ('tipo_lancamento', models.CharField(choices=[('Entrada', 'Entrada (Receita)'), ('Saída', 'Saída (Despesa)'), ('Transferência', 'Transferência Inter-Contas')], max_length=20, verbose_name='Tipo de Lançamento')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição / Histórico')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('data_vencimento', models.DateField(db_index=True, verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data/Hora da Baixa ou Pagamento Real')),
                ('status_pagamento', models.CharField(choices=[('A Vencer', 'A Vencer'), ('Vencido', 'Vencido'), ('Pago', 'Pago'), ('Cancelado', 'Cancelado')], db_index=True, default='A Vencer', max_length=20, verbose_name='Status do Pagamento')),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=500, null=True, verbose_name='Motivo do Cancelamento')),
                ('is_conciliado', models.BooleanField(default=False, verbose_name='Conciliado com Extrato Bancário')),
                ('data_conciliacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Conciliação')),
                ('cartao_credito', models.ForeignKey(blank=True, db_column='cartao_credito_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.cartaocredito', verbose_name='Cartão Corporativo Utilizado')),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.categoriafinanceira', verbose_name='Categoria Financeira')),
                ('conciliado_por', models.ForeignKey(blank=True, db_column='conciliado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_conciliados', to='authentication.usuario', verbose_name='Conciliado por')),
                ('conta', models.ForeignKey(blank=True, db_column='conta_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_origem', to='financeiro.contabancaria', verbose_name='Conta Bancária / Caixa de Origem')),
                ('conta_destino', models.ForeignKey(blank=True, db_column='conta_destino_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_destino', to='financeiro.contabancaria', verbose_name='Conta Bancária de Destino (Transferência)')),
                ('fatura', models.ForeignKey(blank=True, db_column='fatura_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_financeiros', to='faturamento.fatura', verbose_name='Fatura Vinculada')),
                ('fatura_cartao', models.ForeignKey(blank=True, db_column='fatura_cartao_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_fatura', to='financeiro.faturacartao', verbose_name='Fatura do Cartão')),
                ('meio_pagamento', models.ForeignKey(blank=True, db_column='meio_pagamento_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.meiopagamento', verbose_name='Meio de Pagamento')),
            ],
            options={
                'verbose_name': 'Lançamento Financeiro',
                'verbose_name_plural': 'Lançamentos Financeiros',
                'db_table': 'lancamentos_financeiros',
                'ordering': ['-data_vencimento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LogEstorno',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('justificativa', models.TextField(verbose_name='Justificativa Obrigatória do Estorno')),
                ('data_estorno', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora do Estorno')),
                ('lancamento', models.ForeignKey(db_column='lancamento_id', on_delete=django.db.models.deletion.PROTECT, related_name='estornos', to='financeiro.lancamentofinanceiro', verbose_name='Lançamento Estornado')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='estornos_realizados', to='authentication.usuario', verbose_name='Usuário Responsável pelo Estorno')),
            ],
            options={
                'verbose_name': 'Log de Estorno',
                'verbose_name_plural': 'Logs de Estornos',
                'db_table': 'log_estornos',
                'ordering': ['-data_estorno'],
            },
        ),
        migrations.CreateModel(
            name='RegraPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('created_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Criado por (ID do Usuário)')),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Atualizado por (ID do Usuário)')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de Exclusão Lógica')),
                ('deleted_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Excluído por (ID do Usuário)')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Condição Comercial')),
                ('tipo_cobranca', models.CharField(choices=[('A_VISTA', 'À Vista'), ('A_PRAZO', 'A Prazo'), ('PARCELADO', 'Parcelado')], default='A_VISTA', max_length=20, verbose_name='Tipo de Cobrança')),
                ('numero_parcelas', models.IntegerField(default=1, verbose_name='Número de Parcelas')),
                ('prazo_primeira_parcela_dias', models.IntegerField(default=0, verbose_name='Prazo da 1ª Parcela (Dias)')),
                ('intervalo_parcelas_dias', models.IntegerField(default=0, verbose_name='Intervalo entre Parcelas (Dias)')),
                ('desconto_concedido_padrao', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Desconto Padrão Sugerido (%)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Regra Ativa')),
                ('meio_pagamento', models.ForeignKey(db_column='meio_pagamento_id', on_delete=django.db.models.deletion.PROTECT, related_name='regras_pagamento', to='financeiro.meiopagamento', verbose_name='Meio de Pagamento Vinculado')),
            ],
            options={
                'verbose_name': 'Regra de Pagamento / Condição Comercial',
                'verbose_name_plural': 'Regras de Pagamento / Condições Comerciais',
                'db_table': 'regras_pagamento',
                'ordering': ['nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='faturacartao',
            constraint=models.UniqueConstraint(fields=('cartao', 'mes_referencia'), name='unique_cartao_mes_referencia'),
        ),
        migrations.AddIndex(
            model_name='lancamentofinanceiro',
            index=models.Index(fields=['data_vencimento'], name='idx_lanc_vencimento'),
        ),
        migrations.AddIndex(
            model_name='lancamentofinanceiro',
            index=models.Index(fields=['data_pagamento'], name='idx_lanc_pagamento'),
        ),
        migrations.AddIndex(
            model_name='lancamentofinanceiro',
            index=models.Index(fields=['status_pagamento'], name='idx_lanc_status_pagto'),
        ),
    ]
