# Generated by Django 5.2.17 on 2026-08-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriafinanceira',
            name='tipo',
            field=models.CharField(choices=[('RECEITA', 'RECEITA'), ('DESPESA', 'DESPESA'), ('TRANSFERENCIA', 'TRANSFERÊNCIA (NEUTRA PRO DRE)')], default='RECEITA', max_length=20, verbose_name='Tipo de Categoria'),
        ),
        migrations.AlterField(
            model_name='faturacartao',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'ABERTA'), ('FECHADA', 'FECHADA'), ('PAGA', 'PAGA')], default='ABERTA', max_length=20, verbose_name='Status da Fatura do Cartão'),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='status_pagamento',
            field=models.CharField(choices=[('A_VENCER', 'A VENCER'), ('VENCIDO', 'VENCIDO'), ('PAGO', 'PAGO'), ('CANCELADO', 'CANCELADO')], db_index=True, default='A_VENCER', max_length=20, verbose_name='Status do Pagamento'),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='tipo_lancamento',
            field=models.CharField(choices=[('ENTRADA', 'ENTRADA (RECEITA)'), ('SAIDA', 'SAÍDA (DESPESA)'), ('TRANSFERENCIA', 'TRANSFERÊNCIA INTER-CONTAS')], max_length=20, verbose_name='Tipo de Lançamento'),
        ),
    ]
