# Generated by Django 5.2.17 on 2026-09-13 14:34

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_alter_categoriafinanceira_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cartaocredito',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='categoriafinanceira',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='contabancaria',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='faturacartao',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='lancamentofinanceiro',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='meiopagamento',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='regrapagamento',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='categoriafinanceira',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Categoria Ativa'),
        ),
        migrations.AlterField(
            model_name='categoriafinanceira',
            name='tipo',
            field=models.CharField(choices=[('RECEITA', 'RECEITA (ENTRADA)'), ('DESPESA', 'DESPESA (SAÍDA)'), ('AMBOS', 'AMBOS (ENTRADA E SAÍDA)'), ('TRANSFERENCIA', 'TRANSFERÊNCIA (NEUTRA PRO DRE)')], default='RECEITA', max_length=20, verbose_name='Tipo de Categoria'),
        ),
    ]
