# Generated by Django 5.2.17 on 2026-09-13 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_usuario_options_alter_usuario_managers'),
        ('cadastros', '0004_alter_clientefornecedor_managers_and_more'),
        ('faturamento', '0005_alter_fatura_managers'),
        ('financeiro', '0003_alter_cartaocredito_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='cliente_fornecedor',
            field=models.ForeignKey(blank=True, db_column='cliente_fornecedor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_financeiros', to='cadastros.clientefornecedor', verbose_name='Cliente ou Fornecedor Vinculado'),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='fitid',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Identificador Único Bancário (FITID)'),
        ),
        migrations.AddIndex(
            model_name='lancamentofinanceiro',
            index=models.Index(fields=['fitid'], name='idx_lanc_fitid'),
        ),
    ]
