# Generated by Django 5.2.17 on 2026-09-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_lancamentofinanceiro_cliente_fornecedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/%Y/%m/', verbose_name='Comprovante de Pagamento ou Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='nome_arquivo_comprovante',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Arquivo do Comprovante'),
        ),
    ]
