# Generated by Django 5.2.17 on 2026-08-18 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('created_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Criado por (ID do Usuário)')),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Atualizado por (ID do Usuário)')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de Exclusão Lógica')),
                ('deleted_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Excluído por (ID do Usuário)')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='E-mail de Acesso')),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hash da Senha')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('role', models.CharField(choices=[('Admin', 'Administrador'), ('Operador', 'Operador')], default='Operador', max_length=20, verbose_name='Perfil de Acesso')),
                ('pin_hash', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hash do PIN (6 dígitos)')),
                ('tentativas_login_falhas', models.IntegerField(default=0, verbose_name='Tentativas de Login Falhas')),
                ('bloqueado_ate', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado até (Anti-Bruteforce)')),
                ('auth_provider', models.CharField(default='LOCAL', max_length=20, verbose_name='Provedor de Autenticação')),
                ('is_2fa_enabled', models.BooleanField(default=False, verbose_name='2FA Ativado')),
                ('is_ativo', models.BooleanField(default=True, verbose_name='Usuário Ativo')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último Login')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuarios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('acesso_comercial', models.BooleanField(default=False, verbose_name='1. Acesso Comercial (Orçamentos, Faturas e Clientes)')),
                ('acesso_tesouraria', models.BooleanField(default=False, verbose_name='2. Acesso à Tesouraria (Caixa, Conciliação e Estornos)')),
                ('acesso_compras', models.BooleanField(default=False, verbose_name='3. Acesso a Compras (Notas Fiscais de Entrada e Fornecedores)')),
                ('gestao_catalogo', models.BooleanField(default=False, verbose_name='4. Gestão de Catálogo (Itens, Produtos, BOM e Preços)')),
                ('visao_relatorios', models.BooleanField(default=True, verbose_name='5. Visualização de Relatórios (Curvas ABC, Inadimplência e DRE)')),
                ('cadastros_financeiros', models.BooleanField(default=False, verbose_name='6. Cadastros Financeiros (Contas Bancárias, Regras e Categorias)')),
                ('gestao_dicionario_uom', models.BooleanField(default=False, verbose_name='7. Dicionário Central UOM (Unidades de Medida e Atributos)')),
                ('configuracoes_globais', models.BooleanField(default=False, verbose_name='8. Configurações Globais (Empresa, Prazos e SMTP)')),
                ('gestao_equipe', models.BooleanField(default=False, verbose_name='9. Gestão de Equipe (Usuários, Permissões e Desbloqueio)')),
                ('auditoria_logs_recovery', models.BooleanField(default=False, verbose_name='10. Auditoria e Logs (Logs do Servidor, Expurgo e Lixeira Global)')),
                ('usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='authentication.usuario', verbose_name='Usuário Vinculado')),
            ],
            options={
                'verbose_name': 'Permissão',
                'verbose_name_plural': 'Permissões',
                'db_table': 'permissoes',
            },
        ),
    ]
