# Generated by Django 5.2.17 on 2026-08-18 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenSeguranca',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Código / Token Criptográfico')),
                ('tipo', models.CharField(choices=[('RECOVERY', 'Recuperação de Senha'), ('INVITE', 'Convite de Onboarding')], max_length=20, verbose_name='Tipo do Token')),
                ('expira_em', models.DateTimeField(verbose_name='Data/Hora de Expiração')),
                ('utilizado', models.BooleanField(default=False, verbose_name='Token Utilizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='tokens_seguranca', to='authentication.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Token de Segurança',
                'verbose_name_plural': 'Tokens de Segurança',
                'db_table': 'tokens_seguranca',
                'ordering': ['-created_at'],
            },
        ),
    ]
