# Generated by Django 5.2.17 on 2026-09-13 18:50

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_tokenseguranca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'base_manager_name': 'all_objects', 'ordering': ['nome'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
