# Generated by Django 5.2.17 on 2026-08-18 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoGlobal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('validade_orcamento_dias', models.IntegerField(default=15, verbose_name='Validade Padrão de Orçamentos (Dias)')),
                ('taxa_mao_de_obra_hora', models.DecimalField(decimal_places=2, default=80.0, max_digits=10, verbose_name='Taxa de Mão de Obra por Hora (R$)')),
                ('razao_social', models.CharField(default='EMC Soldas LTDA', max_length=255, verbose_name='Razão Social da Oficina')),
                ('cnpj', models.CharField(default='00.000.000/0001-00', max_length=20, verbose_name='CNPJ da Oficina')),
                ('telefone_contato', models.CharField(default='(11) 99999-9999', max_length=20, verbose_name='Telefone de Contato')),
                ('endereco_oficina', models.CharField(default='Rua Industrial, 100 - Oficina', max_length=255, verbose_name='Endereço Completo')),
                ('logo_empresa_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho / URL da Logomarca')),
                ('tempo_ociosidade_minutos', models.IntegerField(default=30, verbose_name='Tempo de Ociosidade para Soft Lock (Minutos)')),
                ('tempo_expiracao_sessao_dias', models.IntegerField(default=15, verbose_name='Validade Mestre da Sessão (Dias)')),
                ('retencao_logs_dias', models.IntegerField(default=30, verbose_name='Retenção de Arquivos de Log (Dias)')),
                ('smtp_host', models.CharField(default='localhost', max_length=255, verbose_name='Servidor SMTP (Host)')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='Porta SMTP')),
                ('smtp_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='Usuário SMTP')),
                ('smtp_password_encrypted', models.TextField(blank=True, null=True, verbose_name='Senha SMTP Criptografada (AES-256)')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Utilizar TLS')),
                ('smtp_use_ssl', models.BooleanField(default=False, verbose_name='Utilizar SSL')),
                ('email_remetente_nome', models.CharField(default='EMC Soldas', max_length=150, verbose_name='Nome do Remetente nos Disparos')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data da Última Alteração')),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Atualizado por (ID do Usuário)')),
            ],
            options={
                'verbose_name': 'Configuração Global',
                'verbose_name_plural': 'Configurações Globais',
                'db_table': 'configuracoes_globais',
            },
        ),
        migrations.CreateModel(
            name='ControleArquivoLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('caminho_arquivo_fisico', models.CharField(max_length=500, unique=True, verbose_name='Caminho Físico do Arquivo (.log)')),
                ('data_criacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Criação do Log')),
                ('data_expurgo_planejada', models.DateField(verbose_name='Data Planejada de Expurgo (TTL)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro no Manifesto')),
            ],
            options={
                'verbose_name': 'Manifesto de Arquivo de Log',
                'verbose_name_plural': 'Manifestos de Arquivos de Log',
                'db_table': 'controle_arquivos_log',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
