# Generated by Django 5.2.17 on 2026-08-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlearquivolog',
            name='caminho_arquivo_fisico',
            field=models.CharField(max_length=255, unique=True, verbose_name='Caminho Físico do Arquivo (.log)'),
        ),
    ]
