# Generated by Django 5.2.17 on 2026-09-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_alter_controlearquivolog_caminho_arquivo_fisico'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoglobal',
            name='aliquota_iss',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5, verbose_name='Alíquota Padrão de ISS Retido (%)'),
        ),
        migrations.AddField(
            model_name='configuracaoglobal',
            name='aliquota_simples_nacional',
            field=models.DecimalField(decimal_places=2, default=8.5, max_digits=5, verbose_name='Alíquota Padrão Simples Nacional (%) - Informativa'),
        ),
    ]
