# Generated by Django 5.2.17 on 2026-08-18 11:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('created_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Criado por (ID do Usuário)')),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Atualizado por (ID do Usuário)')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de Exclusão Lógica')),
                ('deleted_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Excluído por (ID do Usuário)')),
                ('tipo', models.CharField(choices=[('Cliente', 'Cliente'), ('Fornecedor', 'Fornecedor'), ('Ambos', 'Ambos')], default='Cliente', max_length=20, verbose_name='Tipo de Cadastro')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PJ', max_length=2, verbose_name='Tipo de Pessoa')),
                ('nome_razao', models.CharField(db_index=True, max_length=255, verbose_name='Nome / Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('cnpj_cpf', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='CPF / CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30, null=True, verbose_name='Inscrição Estadual')),
                ('isento_ie', models.BooleanField(default=False, verbose_name='Isento de Inscrição Estadual')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone de Contato')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Cliente / Fornecedor',
                'verbose_name_plural': 'Clientes e Fornecedores',
                'db_table': 'clientes_fornecedores',
                'ordering': ['nome_razao'],
                'indexes': [models.Index(fields=['nome_razao'], name='idx_cli_forn_nome_razao'), models.Index(fields=['cnpj_cpf'], name='idx_cli_forn_cnpj_cpf')],
            },
        ),
        migrations.CreateModel(
            name='AnexoGeralCliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_documento', models.CharField(max_length=255, verbose_name='Nome do Documento')),
                ('caminho_arquivo', models.CharField(max_length=500, verbose_name='Caminho do Arquivo Físico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='cadastros.clientefornecedor', verbose_name='Cliente Vinculado')),
            ],
            options={
                'verbose_name': 'Anexo Geral do Cliente',
                'verbose_name_plural': 'Anexos Gerais de Clientes',
                'db_table': 'anexos_gerais_clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('created_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Criado por (ID do Usuário)')),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Atualizado por (ID do Usuário)')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de Exclusão Lógica')),
                ('deleted_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Excluído por (ID do Usuário)')),
                ('identificacao_placa', models.CharField(db_index=True, max_length=50, verbose_name='Identificação / Placa')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Equipamento')),
            ],
            options={
                'verbose_name': 'Equipamento / Veículo',
                'verbose_name_plural': 'Equipamentos e Veículos',
                'db_table': 'equipamentos',
                'ordering': ['identificacao_placa'],
                'indexes': [models.Index(fields=['identificacao_placa'], name='idx_equip_ident_placa')],
            },
        ),
        migrations.CreateModel(
            name='ClienteEquipamento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_vinculo', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Vínculo')),
                ('is_ativo', models.BooleanField(default=True, verbose_name='Vínculo Ativo')),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos_vinculados', to='cadastros.clientefornecedor', verbose_name='Cliente Proprietário')),
                ('equipamento', models.ForeignKey(db_column='equipamento_id', on_delete=django.db.models.deletion.PROTECT, related_name='historico_clientes', to='cadastros.equipamento', verbose_name='Equipamento')),
            ],
            options={
                'verbose_name': 'Vínculo Cliente-Equipamento',
                'verbose_name_plural': 'Vínculos Cliente-Equipamento',
                'db_table': 'cliente_equipamento',
                'ordering': ['-data_vinculo'],
            },
        ),
    ]
