# Generated by Django 5.2.17 on 2026-08-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamento',
            options={'ordering': ['placa', 'identificacao'], 'verbose_name': 'Equipamento / Veículo', 'verbose_name_plural': 'Equipamentos e Veículos'},
        ),
        migrations.RemoveIndex(
            model_name='equipamento',
            name='idx_equip_ident_placa',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='identificacao_placa',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='identificacao',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Identificação Técnica / Frota / Chassi / Código Interno'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='placa',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='Placa do Veículo / Equipamento (Antiga ou Mercosul)'),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['placa'], name='idx_equip_placa'),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['identificacao'], name='idx_equip_identificacao'),
        ),
    ]
