# Generated by Django 5.2.17 on 2026-08-23 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_equipamento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientefornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Principal'),
        ),
        migrations.CreateModel(
            name='ClienteContato',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_contato', models.CharField(max_length=150, verbose_name='Nome do Contato / Responsável')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone de Contato')),
                ('is_whatsapp', models.BooleanField(default=False, verbose_name='Possui WhatsApp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='cadastros.clientefornecedor', verbose_name='Cliente / Fornecedor')),
            ],
            options={
                'verbose_name': 'Contato do Cliente',
                'verbose_name_plural': 'Contatos dos Clientes',
                'db_table': 'clientes_contatos',
                'ordering': ['id'],
            },
        ),
    ]
