# Generated by Django 5.2.17 on 2026-09-13 18:50

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_clientefornecedor_telefone_clientecontato'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='clientefornecedor',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='equipamento',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='clientefornecedor',
            name='iss_retido',
            field=models.BooleanField(default=False, verbose_name='Tomador com Retenção de ISS na Fonte'),
        ),
    ]
