# Generated by Django 5.2.17 on 2026-09-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_clientefornecedor_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientecontato',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='E-mail(s) do Contato'),
        ),
        migrations.AlterField(
            model_name='clientecontato',
            name='telefone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone(s) de Contato'),
        ),
        migrations.AlterField(
            model_name='clientefornecedor',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='E-mail(s) Corporativo / Cobrança'),
        ),
    ]
