# Generated by Django 5.2.17 on 2026-08-18 11:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturaPropostaPagamento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('desconto_personalizado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Desconto Personalizado para a Opção (%)')),
            ],
            options={
                'verbose_name': 'Proposta de Pagamento da Fatura',
                'verbose_name_plural': 'Propostas de Pagamento das Faturas',
                'db_table': 'fatura_propostas_pagamento',
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('created_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Criado por (ID do Usuário)')),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Atualizado por (ID do Usuário)')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de Exclusão Lógica')),
                ('deleted_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Excluído por (ID do Usuário)')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão / Criação do Rascunho')),
                ('data_fechamento', models.DateField(blank=True, db_index=True, null=True, verbose_name='Data de Fechamento / Faturamento Final')),
                ('status', models.CharField(choices=[('Rascunho', 'Rascunho (Pré-Fatura)'), ('Faturada', 'Faturada (Fatura Final)'), ('Paga', 'Paga (Quitada)'), ('Cancelada', 'Cancelada')], db_index=True, default='Rascunho', max_length=20, verbose_name='Status da Fatura')),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Bruto Consolidado (R$)')),
                ('desconto_global', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Desconto Comercial Global (R$)')),
                ('valor_total_faturado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Total Líquido Faturado (R$)')),
                ('numero_nfe_venda', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da NF-e de Venda/Serviço')),
                ('caminho_nfe_pdf', models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho do PDF da DANFE')),
                ('caminho_boleto_pdf', models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho do PDF do Boleto')),
                ('linha_digitavel_boleto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Linha Digitável do Boleto')),
                ('caminho_comprovante_pagamento', models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho do Comprovante de Pagamento')),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=500, null=True, verbose_name='Motivo do Cancelamento')),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='cadastros.clientefornecedor', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Fatura de Cliente',
                'verbose_name_plural': 'Faturas de Clientes',
                'db_table': 'faturas',
                'ordering': ['-id'],
            },
        ),
    ]
