# Generated by Django 5.2.17 on 2026-08-18 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faturamento', '0001_initial'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='regra_pagamento',
            field=models.ForeignKey(blank=True, db_column='regra_pagamento_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='financeiro.regrapagamento', verbose_name='Condição Comercial Definitiva'),
        ),
        migrations.AddField(
            model_name='faturapropostapagamento',
            name='fatura',
            field=models.ForeignKey(db_column='fatura_id', on_delete=django.db.models.deletion.CASCADE, related_name='propostas_pagamento', to='faturamento.fatura', verbose_name='Fatura / Pré-Fatura'),
        ),
        migrations.AddField(
            model_name='faturapropostapagamento',
            name='regra_pagamento',
            field=models.ForeignKey(db_column='regra_pagamento_id', on_delete=django.db.models.deletion.PROTECT, related_name='fatura_propostas', to='financeiro.regrapagamento', verbose_name='Condição Comercial Sugerida'),
        ),
        migrations.AddIndex(
            model_name='fatura',
            index=models.Index(fields=['data_fechamento'], name='idx_fat_data_fechamento'),
        ),
        migrations.AddIndex(
            model_name='fatura',
            index=models.Index(fields=['status'], name='idx_fat_status'),
        ),
        migrations.AddConstraint(
            model_name='faturapropostapagamento',
            constraint=models.UniqueConstraint(fields=('fatura', 'regra_pagamento'), name='unique_fatura_regra_pgto'),
        ),
    ]
