# Generated by Django 5.2.17 on 2026-08-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'RASCUNHO (PRÉ-FATURA)'), ('FATURADA', 'FATURADA (FATURA FINAL)'), ('PAGA', 'PAGA (QUITADA)'), ('CANCELADA', 'CANCELADA')], db_index=True, default='RASCUNHO', max_length=20, verbose_name='Status da Fatura'),
        ),
    ]
