# Generated by Django 5.2.17 on 2026-08-23 15:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0003_alter_fatura_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='data_emissao',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Data de Emissão / Criação do Rascunho'),
        ),
    ]
