# Generated by Django 5.2.17 on 2026-09-13 18:50

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0004_alter_fatura_data_emissao'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='fatura',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
