# Generated by Django 5.2.17 on 2026-08-18 11:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('catalogo', '0001_initial'),
        ('faturamento', '0001_initial'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('created_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Criado por (ID do Usuário)')),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Atualizado por (ID do Usuário)')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de Exclusão Lógica')),
                ('deleted_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Excluído por (ID do Usuário)')),
                ('data_geracao', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Data de Geração')),
                ('data_validade', models.DateField(verbose_name='Data de Validade da Proposta')),
                ('status_operacional', models.CharField(choices=[('Gerado', 'Gerado'), ('Enviado', 'Enviado'), ('Aprovado', 'Aprovado'), ('Em Execução', 'Em Execução'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], db_index=True, default='Gerado', max_length=20, verbose_name='Status Operacional / Produtivo')),
                ('status_financeiro', models.CharField(choices=[('A Faturar', 'A Faturar'), ('Faturado', 'Faturado'), ('Pago', 'Pago'), ('Cancelado', 'Cancelado')], db_index=True, default='A Faturar', max_length=20, verbose_name='Status Financeiro')),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Bruto Total (R$)')),
                ('valor_desconto_aplicado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor de Desconto Aplicado (R$)')),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=500, null=True, verbose_name='Motivo do Cancelamento')),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='cadastros.clientefornecedor', verbose_name='Cliente')),
                ('equipamento', models.ForeignKey(blank=True, db_column='equipamento_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='cadastros.equipamento', verbose_name='Equipamento / Veículo')),
                ('fatura', models.ForeignKey(blank=True, db_column='fatura_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_agrupados', to='faturamento.fatura', verbose_name='Fatura Vinculada')),
            ],
            options={
                'verbose_name': 'Orçamento Comercial',
                'verbose_name_plural': 'Orçamentos Comerciais',
                'db_table': 'orcamentos',
                'ordering': ['-data_geracao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrcamentoItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao_livre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Livre (Lançamento Manual)')),
                ('quantidade', models.DecimalField(decimal_places=4, default=1.0, max_digits=12, verbose_name='Quantidade')),
                ('custo_snapshot', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Custo Unitário Snapshot (R$)')),
                ('valor_venda_snapshot', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor de Venda Unitário Snapshot (R$)')),
                ('item', models.ForeignKey(blank=True, db_column='item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamento_itens', to='catalogo.item', verbose_name='Item / Insumo Simples')),
                ('orcamento', models.ForeignKey(db_column='orcamento_id', on_delete=django.db.models.deletion.CASCADE, related_name='itens_orcamento', to='orcamentos.orcamento', verbose_name='Orçamento Pai')),
                ('produto', models.ForeignKey(blank=True, db_column='produto_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamento_itens', to='catalogo.produto', verbose_name='Produto Composto (BOM)')),
            ],
            options={
                'verbose_name': 'Item do Orçamento',
                'verbose_name_plural': 'Itens do Orçamento',
                'db_table': 'orcamento_itens',
            },
        ),
        migrations.CreateModel(
            name='OrcamentoPropostaPagamento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('desconto_personalizado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Desconto Personalizado (%)')),
                ('orcamento', models.ForeignKey(db_column='orcamento_id', on_delete=django.db.models.deletion.CASCADE, related_name='propostas_pagamento', to='orcamentos.orcamento', verbose_name='Orçamento')),
                ('regra_pagamento', models.ForeignKey(db_column='regra_pagamento_id', on_delete=django.db.models.deletion.PROTECT, related_name='orcamento_propostas', to='financeiro.regrapagamento', verbose_name='Condição Comercial / Regra de Pagamento')),
            ],
            options={
                'verbose_name': 'Proposta de Pagamento do Orçamento',
                'verbose_name_plural': 'Propostas de Pagamento dos Orçamentos',
                'db_table': 'orcamento_propostas_pagamento',
            },
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['data_geracao'], name='idx_orc_data_geracao'),
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['status_operacional'], name='idx_orc_status_oper'),
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['status_financeiro'], name='idx_orc_status_fin'),
        ),
        migrations.AddConstraint(
            model_name='orcamentopropostapagamento',
            constraint=models.UniqueConstraint(fields=('orcamento', 'regra_pagamento'), name='unique_orcamento_regra_pgto'),
        ),
    ]
