# Generated by Django 5.2.17 on 2026-08-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='status_financeiro',
            field=models.CharField(choices=[('A_FATURAR', 'A FATURAR'), ('FATURADO', 'FATURADO'), ('PAGO', 'PAGO'), ('CANCELADO', 'CANCELADO')], db_index=True, default='A_FATURAR', max_length=20, verbose_name='Status Financeiro'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='status_operacional',
            field=models.CharField(choices=[('GERADO', 'GERADO'), ('ENVIADO', 'ENVIADO'), ('APROVADO', 'APROVADO'), ('EM_EXECUCAO', 'EM EXECUÇÃO'), ('CONCLUIDO', 'CONCLUÍDO'), ('CANCELADO', 'CANCELADO')], db_index=True, default='GERADO', max_length=20, verbose_name='Status Operacional / Produtivo'),
        ),
    ]
