# Generated by Django 5.2.17 on 2026-08-23 15:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_alter_orcamento_status_financeiro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='data_geracao',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Data de Geração'),
        ),
    ]
