# Generated by Django 5.2.17 on 2026-09-13 18:50

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0003_alter_orcamento_data_geracao'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orcamento',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
