# Generated by Django 5.2.17 on 2026-08-18 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoFiscalCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('created_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Criado por (ID do Usuário)')),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Atualizado por (ID do Usuário)')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de Exclusão Lógica')),
                ('deleted_by_id', models.BigIntegerField(blank=True, null=True, verbose_name='Excluído por (ID do Usuário)')),
                ('num_nota', models.CharField(db_index=True, max_length=50, verbose_name='Número da Nota Fiscal')),
                ('chave_acesso', models.CharField(blank=True, max_length=44, null=True, verbose_name='Chave de Acesso NFe (44 dígitos)')),
                ('data_compra', models.DateField(db_index=True, verbose_name='Data da Compra')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total da Nota (R$)')),
                ('caminho_arquivo_anexo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho do Anexo (PDF/XML)')),
                ('fornecedor', models.ForeignKey(db_column='fornecedor_id', on_delete=django.db.models.deletion.PROTECT, related_name='documentos_fiscais_compra', to='cadastros.clientefornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Nota Fiscal de Entrada',
                'verbose_name_plural': 'Notas Fiscais de Entrada',
                'db_table': 'documentos_fiscais_compra',
                'ordering': ['-data_compra'],
            },
        ),
        migrations.CreateModel(
            name='NotaCompraItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantidade_comprada', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Quantidade Comprada')),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Valor Unitário de Compra (R$)')),
                ('documento_fiscal', models.ForeignKey(db_column='documento_fiscal_id', on_delete=django.db.models.deletion.CASCADE, related_name='itens_comprados', to='compras.documentofiscalcompra', verbose_name='Nota Fiscal Pai')),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.PROTECT, related_name='historico_compras', to='catalogo.item', verbose_name='Item / Insumo Comprado')),
            ],
            options={
                'verbose_name': 'Item da Nota de Compra',
                'verbose_name_plural': 'Itens das Notas de Compra',
                'db_table': 'nota_compra_itens',
            },
        ),
        migrations.AddIndex(
            model_name='documentofiscalcompra',
            index=models.Index(fields=['num_nota'], name='idx_compra_num_nota'),
        ),
        migrations.AddIndex(
            model_name='documentofiscalcompra',
            index=models.Index(fields=['data_compra'], name='idx_compra_data'),
        ),
        migrations.AddConstraint(
            model_name='notacompraitem',
            constraint=models.UniqueConstraint(fields=('documento_fiscal', 'item'), name='unique_nota_item'),
        ),
    ]
